# Generated by Django 3.1.1 on 2020-09-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Profile',
        ),
    ]
