# Generated by Django 3.1.1 on 2020-10-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDB', '0002_auto_20200930_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
