# Generated by Django 3.1.1 on 2020-10-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testDB', '0004_auto_20201001_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplemodel',
            name='description',
        ),
    ]
